<?php

namespace frontend\controllers;
use frontend\components\ParamsTrait;

use yii\base\ErrorException;
use yii\web\Controller;
use Yii;  //需要引用   Yii::$app
/**
 * Site controller
 */
class BaseController extends Controller
{
    use ParamsTrait;

    public function init()
    {
     echo    Yii::$app->request->post('token');exit;


        parent::init(); // TODO: Change the autogenerated stub
        //验证登录
        $this->chechxLogin();
    }

    //验证登录
    private function chechxLogin(){
      //  $route = Yii::$app->controller->route;
        $route = Yii::$app->requestedRoute;
        $loginAccess = Yii::$app->params['not_login'];

        //无法登录的跳过
        if(in_array($route,$loginAccess)){
            return  true;
        }


        //查询用户
        $userUid = Yii::$app->user->id;

        var_dump($userUid);exit;


        if (!$userUid) { // 无效的token
            throw new ErrorException(301);
        }

        return true;

    }
}
