<?php

namespace api\controllers;
use api\components\ParamsTrait;

use api\components\Userinfo;
use yii\base\ErrorException;
use yii\web\Controller;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\ContentNegotiator;
use yii\web\Response;
use api\services\UserService;
use yii\filters\auth\QueryParamAuth;
use Yii;  //需要引用   Yii::$app
/**
 * Site controller
 */
class BaseController extends Controller
{
    use ParamsTrait;
    /*public  $_user;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->_user = Userinfo::findIdentityByAccessToken(\Yii::$app->request->post('token'));


        //验证登录
        $this->chechxLogin();
    }*/

    //验证登录
    private function chechxLogin(){
      //  $route = Yii::$app->controller->route;


        return true;

    }


    public $modelClass = 'app\models\User';

    public $post;
    public $get;
    public $_user;
    public $_userId;
    public $optional = [
      'login'
    ];
    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
      //  $this->_user = UserService::findIdentityByAccessToken(Yii::$app->request->headers->get('user-token'));

    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
      /*  $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => ['login']
        ];*/

        $route = Yii::$app->requestedRoute;
        $loginAccess = Yii::$app->params['access'];

        //无法登录的跳过
        if(in_array($route,$loginAccess)){
            $behaviors['authenticator'] = [
                /*'class' => CompositeAuth::className(),
                'authMethods' => [
                    QueryParamAuth::className(),
                ],*/
                'class' => QueryParamAuth::className(),
                'optional'=>$this->optional  //设置无需登录得action
            ];
        }

        return $behaviors;
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->post = Yii::$app->request->post();
        $this->get = Yii::$app->request->get();
        $this->_user = Yii::$app->user->identity;
        $this->_userId = Yii::$app->user->id;
        return $action;
    }

}
